version: "3.9"
services:
  jupyter:
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"
    volumes: 
      - ./notebooks:/home/jovyan/work
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION=${REGION}